### ISSUE TITLE
can not import the urdf environment from gazebo simulation

### ISSUE THREAD

**Issue by LJoson** [rise-lab-skku/ICRA2023_Quadruped_Robot_Challenges#2]
hi,i find that can not import the urdf environment from gazebo simulation, but the rviz is normal，here is my env

ubuntu 18.04 ros1 melodic
4070ti 
gazebo11

so ,i want to know what ican do to import the urdf

**Comment by HukoOo** [comment]
can you attach error messages when you import urdf?

**Comment by LJoson** [comment]
> can you attach error messages when you import urdf?

nice thank you for your reply,here is the log

`... logging to /home/lj/.ros/log/b2b06942-4d45-11ee-b539-000c29d33d73/roslaunch-ubuntu-5592.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://ubuntu:39819/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /map_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.13
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    urdf_spawner (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [5619]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b2b06942-4d45-11ee-b539-000c29d33d73
process[rosout-1]: started with pid [5637]
started core service [/rosout]
process[gazebo-2]: started with pid [5643]
process[gazebo_gui-3]: started with pid [5649]
process[urdf_spawner-4]: started with pid [5652]
[ INFO] [1694067225.302561417]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1694067225.304104985]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1694067225.333255188]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1694067225.334667295]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[INFO] [1694067225.500463, 0.000000]: Loading model XML from ros parameter map_description
[INFO] [1694067225.502979, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1694067225.577382018]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1694067225.604219517]: Physics dynamic reconfigure ready.
[INFO] [1694067225.805623, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1694067225.988495, 0.000000]: Spawn status: SpawnModel: Successfully spawned entity
[INFO] [1694067225.989805, 0.000000]: Unpausing physics
[urdf_spawner-4] process has finished cleanly
log file: /home/lj/.ros/log/b2b06942-4d45-11ee-b539-000c29d33d73/urdf_spawner-4*.log

libcurl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to fuel.gazebosim.org:443 

libcurl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to fuel.ignitionrobotics.org:443 
`
What makes me very confused is that rviz can be visualized normally, and I have tried different ros versions and gazebo version settings on multiple computers, and the situation is still the same

**Comment by LJoson** [comment]
also i can not find something wrong,just run `roslaunch quadruped_competition gazebo_world.launch` rename [ICRA2023_Quadruped_Robot_Challenges](https://github.com/rise-lab-skku/ICRA2023_Quadruped_Robot_Challenges) ->quadruped_competition

**Comment by HukoOo** [comment]
try to launch again without renaming the ROS package (ICRA2023_Quadrusted_Robot_Challenges)

**Comment by LJoson** [comment]
> try to launch again without renaming the ROS package (ICRA2023_Quadrusted_Robot_Challenges)

why i renaming the ROS package，because when run `roslaunch ICRA2023_Quadruped_Competition gazebo_world.launch`,hereis log 

`(base) lj@LJoson:~/quad_ws$ roslaunch ICRA2023_Quadruped_Competition gazebo_world.launch
WARNING: Package name "ICRA2023_Quadruped_Competition" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
... logging to /home/lj/.ros/log/949dbd8a-4d52-11ee-b993-00155dd2c3af/roslaunch-LJoson-22308.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

WARNING: Package name "ICRA2023_Quadruped_Competition" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://LJoson:38973/

SUMMARY
========

PARAMETERS
 * /gazebo/enable_ros_network: True
 * /map_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.13
 * /use_sim_time: True

NODES
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    spawn_urdf (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [22330]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 949dbd8a-4d52-11ee-b993-00155dd2c3af
WARNING: Package name "ICRA2023_Quadruped_Competition" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
process[rosout-1]: started with pid [22341]
started core service [/rosout]
process[gazebo-2]: started with pid [22344]
process[gazebo_gui-3]: started with pid [22347]
process[spawn_urdf-4]: started with pid [22354]
WARNING: Package name "ICRA2023_Quadruped_Competition" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "ICRA2023_Quadruped_Competition" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "ICRA2023_Quadruped_Competition" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
WARNING: Package name "ICRA2023_Quadruped_Competition" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
[ INFO] [1694072758.222356361]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1694072758.222924983]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1694072758.230163047]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1694072758.230936611]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1694072758.509230614]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1694072758.521989758, 0.006000000]: Physics dynamic reconfigure ready.
[spawn_urdf-4] process has finished cleanly
log file: /home/lj/.ros/log/949dbd8a-4d52-11ee-b993-00155dd2c3af/spawn_urdf-4*.log
`
something warning in log ,and still can't visualize。
![image](https://github.com/rise-lab-skku/ICRA2023_Quadruped_Robot_Challenges/assets/47655124/98cae660-2b3f-44bb-8d67-e2d9596b7630)

**Comment by LJoson** [comment]
so i want to know if my pc performance is not enough，but i test it on 4070ti(so sad)

**Comment by HukoOo** [comment]
You can ignore package name warning. 

If the gazebo screen pops up without an error message, wait a few minutes for the map to load.

In my experience, the loading was slow because the map is one stl file.

**Comment by LJoson** [comment]
now 

> You can ignore package name warning.
> 
> If the gazebo screen pops up without an error message, wait a few minutes for the map to load.
> 
> In my experience, the loading was slow because the map is one stl file.

Ten minutes have passed, still nothing

**Comment by LJoson** [comment]
ok,Finally, I would like to ask one thing. What tools are generally used to design map scenes like this?
